language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t ajpj40/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ajpj40/react-test npm test

after_success:
  - docker build -t ajpj40/multi-client ./client
  - docker build -t ajpj40/multi-nginx ./nginx
  - docker build -t ajpj40/multi-server ./server
  - docker build -t ajpj40/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push ajpj40/multi-client
  - docker push ajpj40/multi-nginx
  - docker push ajpj40/multi-server
  - docker push ajpj40/multi-worker
